using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using DTO;
using CAD;
using System.Data;

namespace APPEventNow
{
    /// <summary>
    /// Lógica de interacción para Busqueda_Eliminar.xaml
    /// </summary>
    public partial class Busqueda_Eliminar : Window
    {
        public Busqueda_Eliminar()
        {
            InitializeComponent();
        }
        //Evento del boton eliminar 
        private void eliminarEvento(object sender, RoutedEventArgs e)
        {
            int filas = 0;
            Evento elim = new Evento();
            string id;
            id = txtIdEliminar.Text;

            if(txtIdEliminar.Text == "")
            {
                MessageBox.Show("Complete el campo");
            }
             else if (id.Any(x=> char.IsLetter(x)))
            {
                MessageBox.Show("No se permiten Letras");
            }
            else
            {
                elim.id_e = Int32.Parse(id);
                Conexion op = new Conexion();
                filas = op.EliminarEvento(elim);
                if (filas > 0)
                {
                    MessageBox.Show("Evento Eliminado");
                    clear();
                }
                else
                {
                    MessageBox.Show("Evento no eliminado");
                }
            }
        }
        //Evento del boton buscar
        private void Buscar(object sender, RoutedEventArgs e)
        {
            Evento search = new Evento();
            search.titulo_e = txtTitulo.Text;
            search.categoria_e = txtCategoria.Text;

            if (String.IsNullOrEmpty(search.titulo_e) &&
              String.IsNullOrEmpty(search.categoria_e))
            {
                MessageBox.Show("Complete alguno de los dos campos");
            }
            else
            {
                Conexion op = new Conexion();
                DataTable dt = op.Buscar_titulo_categoria(search);
                if (dt.Rows.Count > 0)
                {
                    listar.DataContext = dt.DefaultView;
                }
                else
                {
                    listar.DataContext = "No se encontraron datos";
                }
            }
        }
        //listar eventos en datagrid
        private void listar_AutoGeneratedColumns(object sender, EventArgs e)
        {
            if (listar.Columns.Count > 0)
            {
                //Definir los nombres de las columnas de la tabla
                listar.Columns[0].Header = "# ID";
                listar.Columns[1].Header = "Categoria";
                listar.Columns[2].Header = "Titulo";
                listar.Columns[3].Header = "Descripcion";
                listar.Columns[4].Header = "Foto";
                listar.Columns[5].Header = "Ubicacion";
                listar.Columns[6].Header = "Fecha";
                listar.Columns[7].Header = "Hora Inicio";
                listar.Columns[8].Header = "Hora Fin";
                listar.Columns[9].Header = "Entidad";
                listar.Columns[10].Header = "Tipo";
                
            }
            else
            {
                Console.WriteLine("Holamundo");
            }
        }
        //Cerrar Main
        private void Cerrar(object sender, RoutedEventArgs e)
        {
            GestionEventos back = new GestionEventos();
            App.Current.MainWindow = back;
            this.Close();
            back.Show();
        }
        private void Back(object sender, RoutedEventArgs e)
        {
            GestionEventos back = new GestionEventos();
            App.Current.MainWindow = back;
            this.Close();
            back.Show();
        }
        private void clear()
        {
            txtCategoria.Text = null;
            txtTitulo.Text = null;
        }

    }
}
